<?= $this->partial('common/header.phtml', $this) ?>
<h1>活動：<?= $this->escape($this->event->name) ?></h1>
<hr>
<h2>我要錄自介</h2>
<?php if ($this->user) { ?>
<form method="post" action="/event/saveintro/<?= $this->event->id ?>">
<input type="hidden" name="record_data" value="">
<input type="hidden" name="record_length" value="">
<input type="hidden" name="record_type" value="">
Slack 帳號：<?= $this->escape(Pix_Session::get('account')) ?><br>
<input type="hidden" name="avatar" value="<?= $this->escape(Pix_Session::get('image')) ?>">
<input type="hidden" name="account" value="<?= $this->escape(Pix_Session::get('account')) ?>">
<input type="hidden" name="display_name" value="<?= $this->user->name ?>">
顯示頭像：<img src="<?= $this->escape(Pix_Session::get('image')) ?>" width="128" height="128"><br>
顯示名稱：<?= $this->escape($this->user->name) ?><br>
(若想變更頭像或是顯示名稱，請至 slack 變更並在這邊重新登入)<br>
<?php if (!$this->intro) { ?>
三個關鍵字：<input type="text" name="keyword"><br>
錄音：<button id="record">按我錄音</button>
<button id="replay" style="display:none">按我聽錄音</button>
<audio id="replay-audio"></audio>
<span id="record-time">(目前沒有錄音，若不錄音將會以語音念出您的三個關鍵字）</span><br>
<?php } else { ?>
<?php $data = json_decode($this->intro->data) ?>
三個關鍵字：<input type="text" name="keyword" value="<?= $this->escape($data->keyword) ?>"><br>
錄音：<button id="record">按我錄音</button>
<button id="replay" style="display:none">按我聽錄音</button>
<audio id="replay-audio"></audio>
<span id="record-time">(目前沒有錄音，若不錄音將會以語音念出您的三個關鍵字）</span><br>
<?php if ($data->voice_path) { ?>
<script>
$('#replay-audio')[0].src = 'https://g0v-intro.s3-ap-northeast-1.amazonaws.com/' + <?= json_encode($data->voice_path) ?>;
record_length = <?= intval($data->voice_length) / 1000 ?>;
$('[name="record_length"]').val(record_length * 1000);
$('[name="record_data"]').val('no-change:' +  <?= json_encode($data->voice_path) ?>);
$('#replay').show();
$('#record-time').text('有錄音記錄，錄音長度 ' + record_length.toPrecision(2) + ' 秒');

</script>
<?php } ?>
<?php } ?>
<button type="submit">儲存</button>
</form>
<script>
var recorder;

setInterval(function(){
	if ($('#record').data('record_at')) {
		var delta = ((new Date).getTime() - $('#record').data('record_at')) / 1000;
		$('#record-time').text('錄音中：' + delta.toPrecision(2) + ' 秒');
		if (delta > 10) {
			recordButtonClick();
		}
	}
}, 100);

var perm_asked = false;
var recordButtonClick = function(e){
	e.preventDefault();
    if (!perm_asked) {
        if ('undefined' === typeof(MediaRecorder)) {
            alert('iPhone 不支援錄音功能，請更換非 iOS 系統（電腦或是 Android 系統）');
            return;
      }
      // get audio stream from user's mic
      navigator.mediaDevices.getUserMedia({
        audio: true
      })
      .then(function (stream) {
        recorder = new MediaRecorder(stream);
         

        // listen to dataavailable, which gets triggered whenever we have
        // an audio blob available
        recorder.addEventListener('dataavailable', onRecordingReady);
        $('#record').click();
      });
      perm_asked = true;
      return;
    }
	if ($(this).data('record_at')) { // 已經有錄了
		var delta = ((new Date).getTime() - $('#record').data('record_at')) / 1000;
		$(this).data('record_length', delta);
		$(this).data('record_at', null);
		$(this).text('按我錄音');
		recorder.stop();
	} else {
		$(this).data('record_at', new Date);
		$('#replay').hide();
		$(this).text('結束錄音');
		recorder.start();
	}
};

var onRecordingReady = function(e){
	if (e.data.size == 0) {
        alert('錄音失敗，請確認是否有接麥克風');
        return;
}
    var reader = new FileReader();
    reader.addEventListener("loadend", function() {
       // reader.result contains the contents of blob as a typed array
        $('[name="record_data"]').val(btoa(reader.result.toString()));
    });
    reader.readAsBinaryString(e.data);
    $('#replay-audio')[0].src = URL.createObjectURL(e.data);
    $('[name="record_length"]').val($('#record').data('record_length') * 1000);
    $('[name="record_type"]').val(e.data.type);
	$('#replay').show();
	$('#record-time').text('錄音完成，錄音長度 ' + $('#record').data('record_length').toPrecision(2) + ' 秒');
};

$('#replay').click(function(e){
	e.preventDefault();
	$('#replay-audio')[0].play();
});

recordButton = document.getElementById('record');
recordButton.addEventListener('click', recordButtonClick);

</script>
<?php } else { ?>
您需要有 g0v slack 帳號並在這邊登入才可以錄自介喔。<br>
註冊帳號請按<a href="https://join.g0v.tw">這裡</a><br>
已經有 slack 帳號請按<a href="/login/?next=<?= urlencode($_SERVER['REQUEST_URI']) ?>">登入</a><br>
<?php } ?>
<hr>
<h2>其他人的自介</h2>
<ul class="thumbnails">
    <?php foreach (Intro::search(array('event' => $this->event->id))->order('created_at ASC') as $intro) { ?>
    <?php $data = json_decode($intro->data) ?>
    <li class="span2">
    <div class="thumbnail">
        <img src="<?= $this->escape($data->avatar) ?>" width="128" height="128" alt="">
        <h3>@<?= $this->escape($data->account) ?></h3>
        顯示名稱：<?= $this->escape($data->display_name) ?><br>
        <p style="word-wrap: break-word; ">關鍵字：<?= $this->escape($data->keyword) ?></p>
        <?php if ($data->voice_path) { ?>
        <p><a href="#" class="btn btn-primary play-voice" data-path="<?= $this->escape($data->voice_path) ?>" data-id="<?= $intro->id ?>">播放自介</a></p>
        <?php } ?>
    </li>
    <?php } ?>
</ul>
<script>
$('.play-voice').click(function(e){
    e.preventDefault();
    var audio_dom = $('<audio></audio>');
    audio_dom[0].src = 'https://g0v-intro.s3-ap-northeast-1.amazonaws.com/' + $(this).data('path');
    audio_dom[0].play();
});
</script>
<?= $this->partial('common/footer.phtml', $this) ?>
