<?= $this->partial('common/header.phtml', $this) ?>
<script src="https://cdn.jsdelivr.net/npm/opus-media-recorder@latest/OpusMediaRecorder.umd.js"></script>
<script src="https://cdn.jsdelivr.net/npm/opus-media-recorder@latest/encoderWorker.umd.js"></script>
<h1>活動：<?= $this->escape($this->event->name) ?></h1>
<hr>
<h2>我要錄自介</h2>
<?php if ($this->user) { ?>
<form method="post" action="/event/saveintro/<?= $this->event->id ?>">
<input type="hidden" name="record_data" value="">
<input type="hidden" name="record_length" value="">
<input type="hidden" name="record_type" value="">
Slack 帳號：<?= $this->escape(Pix_Session::get('account')) ?><br>
<input type="hidden" name="avatar" value="<?= $this->escape(Pix_Session::get('image')) ?>">
<input type="hidden" name="account" value="<?= $this->escape(Pix_Session::get('account')) ?>">
<input type="hidden" name="display_name" value="<?= $this->user->name ?>">
顯示頭像：<img src="<?= $this->escape(Pix_Session::get('image')) ?>" width="128" height="128"><br>
顯示名稱：<?= $this->escape($this->user->name) ?><br>
<div class="alert alert-primary" role="alert">
    (若想變更頭像或是顯示名稱，請至 slack 變更並在這邊重新登入)
</div>
<div class="input-group">
    <div class="input-group-prepend">
        <span class="input-group-text">三個關鍵字</span>
    </div>
    <input type="text" class="form-control" name="keyword">
</div>
錄音：<button id="record" class="btn btn-primary">按我錄音</button>
<button id="replay" style="display:none" class="btn btn-primary">按我聽錄音</button>
<audio id="replay-audio"></audio>
<div id="record-time" class="alert alert-primary" role="alert">(目前沒有錄音，若不錄音將會以語音念出您的三個關鍵字）</div>
<?php if ($this->intro) { ?>
<?php $data = json_decode($this->intro->data) ?>
<script>
$('[name="keyword"]').val(<?= json_encode($data->keyword) ?>);
<?php if ($data->voice_path) { ?>
$('#replay-audio')[0].src = 'https://g0v-intro.s3-ap-northeast-1.amazonaws.com/' + <?= json_encode($data->voice_path) ?>;
record_length = <?= intval($data->voice_length) / 1000 ?>;
$('[name="record_length"]').val(record_length * 1000);
$('[name="record_data"]').val('no-change:' +  <?= json_encode($data->voice_path) ?>);
$('#replay').show();
$('#record-time').text('有錄音記錄，錄音長度 ' + record_length.toPrecision(2) + ' 秒');
<?php } ?>
</script>
<?php } ?>
<button type="submit" class="btn btn-primary">儲存</button>
</form>
<script>
var recorder;

setInterval(function(){
	if ($('#record').data('record_at')) {
		var delta = ((new Date).getTime() - $('#record').data('record_at')) / 1000;
		$('#record-time').text('錄音中：' + delta.toPrecision(2) + ' 秒');
		if (delta > 10) {
			recordButtonClick();
		}
	}
}, 100);

var perm_asked = false;
var recordButtonClick = function(e){
	e.preventDefault();
    if (!perm_asked) {
      // get audio stream from user's mic
      navigator.mediaDevices.getUserMedia({
        audio: true
      })
      .then(function (stream) {
        workerOptions = {};
        if ('undefined' === typeof(MediaRecorder)) {
            workerOptions = {
                OggOpusEncoderWasmPath: 'https://cdn.jsdelivr.net/npm/opus-media-recorder@latest/OggOpusEncoder.wasm',
                WebMOpusEncoderWasmPath: 'https://cdn.jsdelivr.net/npm/opus-media-recorder@latest/WebMOpusEncoder.wasm'
        };
        window.MediaRecorder = OpusMediaRecorder;
      }
        recorder = new MediaRecorder(stream, {}, workerOptions);
         

        // listen to dataavailable, which gets triggered whenever we have
        // an audio blob available
        recorder.addEventListener('dataavailable', onRecordingReady);
        $('#record').click();
      });
      perm_asked = true;
      return;
    }
	if ($(this).data('record_at')) { // 已經有錄了
		var delta = ((new Date).getTime() - $('#record').data('record_at')) / 1000;
		$(this).data('record_length', delta);
		$(this).data('record_at', null);
		$(this).text('按我錄音');
		recorder.stop();
	} else {
		$(this).data('record_at', new Date);
		$('#replay').hide();
		$(this).text('結束錄音');
		recorder.start();
	}
};

var onRecordingReady = function(e){
	if (e.data.size == 0) {
        alert('錄音失敗，請確認是否有接麥克風');
        return;
}
    var reader = new FileReader();
    reader.addEventListener("loadend", function() {
       // reader.result contains the contents of blob as a typed array
        $('[name="record_data"]').val(btoa(reader.result.toString()));
    });
    reader.readAsBinaryString(e.data);
    $('#replay-audio')[0].src = URL.createObjectURL(e.data);
    $('[name="record_length"]').val($('#record').data('record_length') * 1000);
    $('[name="record_type"]').val(e.data.type);
	$('#replay').show();
	$('#record-time').text('錄音完成，錄音長度 ' + $('#record').data('record_length').toPrecision(2) + ' 秒');
};

$('#replay').click(function(e){
	e.preventDefault();
	$('#replay-audio')[0].play();
});

recordButton = document.getElementById('record');
recordButton.addEventListener('click', recordButtonClick);

</script>
<?php } else { ?>
您需要有 g0v slack 帳號並在這邊登入才可以錄自介喔。<br>
註冊帳號請按<a href="https://join.g0v.tw">這裡</a><br>
已經有 slack 帳號請按<a href="/login/?next=<?= urlencode($_SERVER['REQUEST_URI']) ?>">登入</a><br>
<?php } ?>
<hr>
<h2>其他人的自介</h2>
<a href="/event/downloadcsv/<?= $this->event->id ?>">下載成CSV</a>
<a href="/event/data/<?= $this->event->id ?>">API</a>
<style>
@media (min-width: 576px) {  .card-columns { column-count: 2; } } @media (min-width: 768px) { .card-columns {  column-count: 3; } }  @media (min-width: 992px) { .card-columns {  column-count: 4; } }  @media (min-width: 1200px) { .card-columns {  column-count: 5; } }
</style>
<div class="card-columns">
    <?php foreach (Intro::search(array('event' => $this->event->id))->order('created_at ASC') as $intro) { ?>
    <?php $data = json_decode($intro->data) ?>
    <div class="card">
        <img class="card-img" src="<?= $this->escape($data->avatar) ?>" alt="">
        <div class="card-body">
        <h3 class="card-title">@<?= $this->escape($data->account) ?></h3>
        <p class="card-text">顯示名稱：<?= $this->escape($data->display_name) ?></p>
        <p class="card-text" style="word-wrap: break-word; ">關鍵字：<?= $this->escape($data->keyword) ?></p>
        </div>
        <div class="card-footer">
        <?php if ($data->voice_path) { ?>
        <p><a href="#" class="btn btn-primary play-voice" data-path="<?= $this->escape($data->voice_path) ?>" data-id="<?= $intro->id ?>">播放自介</a></p>
        <?php } else { ?>
        <p><a href="#" class="btn btn-primary play-tts" data-text="<?= $this->escape($data->display_name . ' ' . $data->keyword) ?>">機器發音</a></p>
        <?php } ?>
        </div>
    </div>
    <?php } ?>
</div>
<script>
$('.play-voice').click(function(e){
    e.preventDefault();
    var audio_dom = $('<audio></audio>');
    audio_dom[0].src = 'https://g0v-intro.s3-ap-northeast-1.amazonaws.com/' + $(this).data('path');
    audio_dom[0].play();
    });
$('.play-tts').click(function(e){
    e.preventDefault();
    speechSynthesis.speak(new SpeechSynthesisUtterance($(this).data('text')));
});
</script>
<?= $this->partial('common/footer.phtml', $this) ?>
