
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>g0v helper</title>
<script src="//ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.css">
<script>
$(function(){
	$.get(<?= json_encode($this->api) ?>, function(ret){
		for (var i = 0; i < ret.data.length; i ++) {
            intro = ret.data[i];
			var dom = $($('#tmpl-slide').html());
			$('img', dom).attr('src', intro.user.avatar);
			$('h5', dom).text('@' + intro.user.account);
			$('p', dom).text(intro.intro.keyword);
			$('.no', dom).text((i + 1) + '/' + ret.data.length);
			dom.data('data', intro);
			$('.carousel-inner').append(dom);
		}
		$('.carousel-item:first').addClass('active');

		$('.carousel').on('slide.bs.carousel', function (e) {
		  // do something...
		});
	}, 'json');

    $('.carousel').carousel('next').carousel({interval: 5000, ride: true, pause: false});
});


</script>
</head>
<body>
<style>
.carousel-item .d-none {
	text-shadow:
	-1px -1px 0 #000,
	1px -1px 0 #000,
	-1px 1px 0 #000,
	1px 1px 0 #000,
	2px 2px 2px black;
	color: white;
	position: absolute;
	left: 300px;
	top: 0px;
}
.carousel-item {
	text-align: center;
}
.carousel-item h5 {
	font-size: 6rem;
}
.carousel-item p {
	font-size: 3rem;
}
.no {
	position: absolute;
	right: 0px;
	bottom: 0px;
}
</style>
<script id="tmpl-slide" type="text/html">
    <div class="carousel-item">
      <img src="" class="d-block" alt="..." width="256" height="256" style="float:left">
      <div class="d-none d-md-block" style="float:left">
        <h5></h5>
        <p></p>
		<div class="no"></div>
      </div>
    </div>
</script>
<div class="container-fluid">
<div id="carouselExampleCaptions" class="carousel slide" style="height: 100%" data-pause="false">
  <div class="carousel-inner">
  </div>
  <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</div>
</body>
</html>
