<?= $this->partial('/common/header.phtml', $this) ?>
<script src="https://meet.jit.si/libs/lib-jitsi-meet.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" />
<style>
body, div.container-fluid {
    height: 100%;
    max-height: 100%;
}
#feature-area {
    position: fixed;
    top: 62px;
	width: 90%;
}
#member-area {
    position: fixed;
    width: 140px;
    top: 56px;
    right: 0px;
    height: 100%;
    border: 1px solid black;
    text-align: center;
}

#member-list .v-1,.v-2,.v-3,.v-4,.v-5 {
	opacity: 0%;
	position: absolute;
	left: 0px;
}
#member-list .v-1 {
	top: 0px;
}
#member-list .v-2 {
	top: 20px;
}
#member-list .v-3 {
	top: 40px;
}
#member-list .v-4 {
	top: 60px;
}
#member-list .v-5 {
	top: 80px;
}

#member-list {
    overflow-x: hidden;
    overflow-y: auto;
    height: 100%;
}
.member-box {
    height: 128px;
    width: 128px;
    position: relative;
}
.member-avatar {
    width: 128px;
    height: 128px;
    border: 1px solid black;
}
.member-video {
    width: 128px;
    height: 128px;
    border: 1px solid black;
    position: absolute;
    top: 0px;
    left: 0px;
    display: none;
}
.member-box.has-video .member-video {
    display: block;
}
.member-box.has-video .member-avatar {
    width: 32px;
    height: 32px;
}
.member-box.has-video .member-image {
    width: 32px;
    height: 32px;
    opacity: 50%;
}
.member-status {
	position: absolute;
	top: 0px;
	right: 0px;
}

.member-displayname {
    position: absolute;
    top: 105px;
    left: 4px;
    background-color: rgba(255,255,255,0.5);
}
.member-talking { background-color: yellow; }
#main-area {
    position: fixed;
    left: 0px;
    bottom: 0px;
    top: 110px;
    right: 140px;
    border: 1px solid black;
}
html {
        height: 100%;
}
.col {
    height: 100%;
    max-height: 100%;
    overflow: scroll;
}
#message {
    overflow: scroll;
    height: 100%;
}
</style>
<div id="feature-area">
    <h1 style="display: inline; float: left; width: 40%"><input type="text" id="title" value="" readonly="readonly"  style="width: 100%"></h1>
	<div class="list-group list-group-horizontal">
		<a href="#" class="list-group-item active main-switch" id="main-switch-hackmd">共筆</a>
		<a href="#" class="list-group-item main-switch" id="main-switch-video">影音畫面</a>
        <div class="list-group-item">
        <div class="custom-control custom-switch" style="float: left">
            <input type="checkbox" class="custom-control-input" id="auth-microphone">
            <label class="custom-control-label" for="auth-microphone">麥克風</label>
        </div>
        </div>
        <div class="list-group-item">
        <div class="custom-control custom-switch" style="float: left">
            <input type="checkbox" class="custom-control-input" id="auth-camera">
            <label class="custom-control-label" for="auth-camera">攝影機</label>
        </div>
        </div>
        <div class="list-group-item">
        <div class="custom-control custom-switch" style="float: left">
            <input type="checkbox" class="custom-control-input" id="auth-screen">
            <label class="custom-control-label" for="auth-screen">螢幕分享</label>
        </div>
        </div>
        <div class="list-group-item" id="attach-audio-area">
			<a id="attach-audio-button" href="#">沒聲音?</a>
        </div>
    </div>
</div>
<div id="main-area">
	<div class="main-area-section" id="main-area-hackmd" style="width: 100%; height: 100%">
        <iframe src="https://g0v.hackmd.io/@jothon/hsiaothon/" style="width: 100%; height: 100%"></iframe>
    </div>
    <div class="main-area-section" id="main-area-video" style="width: 100%; height: 100%; display:none; ">
		<video autoplay="1" style="width: 100%; height: 100%" id="track-video"></video>
    </div>
</div>
<div id="member-area">
    <h3>成員名單</h3>
<script id="tmpl-member-box" type="text/html">
<div class="member-box">
<div class="member-avatar">
<img class="member-image" src="" width="120" height="120" style="display:none">
<div class="member-nointro" style="display:none">無自介使用者</div>
</div>
<video class="member-video" autoplay="1"></video>
<span class="member-displayname">Fellow Jitster</span>
<span class="member-status">
<i class="microphone-status fas fa-microphone-alt"></i>
<i class="video-status fas fa-video"></i>
</span>
<span class="v-all v-1 v-a"><i class="fas fa-circle"></i></span>
<span class="v-all v-2 v-b"><i class="fas fa-circle"></i></span>
<span class="v-all v-3 v-c"><i class="fas fa-circle"></i></span>
<span class="v-all v-4 v-b"><i class="fas fa-circle"></i></span>
<span class="v-all v-5 v-a"><i class="fas fa-circle"></i></span>
</div>
</script>
<div id="member-list">
	<div class="member-box" id="member-me" style="display:none">
	<div class="member-avatar">
	<img class="member-image" src="" width="120" height="120">
	</div>
    <video class="member-video" autoplay="1"></video>
	<span class="member-displayname">Me</span>
	<span class="member-status">
		<i class="microphone-status fas fa-microphone-alt-slash"></i>
		<i class="video-status fas fa-video-slash"></i>
	</span>
	<span class="v-all v-1 v-a"><i class="fas fa-circle"></i></span>
	<span class="v-all v-2 v-b"><i class="fas fa-circle"></i></span>
	<span class="v-all v-3 v-c"><i class="fas fa-circle"></i></span>
	<span class="v-all v-4 v-b"><i class="fas fa-circle"></i></span>
	<span class="v-all v-5 v-a"><i class="fas fa-circle"></i></span>
	</div>
</div><!-- #member-list -->
</div><!-- #member-area -->
<script>
/* global $, JitsiMeetJS */

const options = {
    hosts: {
        domain: 'meet.jit.si',
        muc: 'conference.meet.jit.si'
    },
    bosh: '//meet.jit.si/http-bind',

   // The name of client node advertised in XEP-0115 'c' stanza
   clientNode: 'http://jitsi.org/jitsimeet'
};

var confOptions = {
    openBridgeChannel: true,
    confID: 'g0v-test',
};

let connection = null;
let room = null;

function track_video_attach(track) {
	if (old_track = $('#track-video').data('track')) {
		old_track.detach($('#track-video')[0]);
	}
	track.attach($('#track-video')[0]);
};

/**
 * Handles local tracks.
 * @param tracks Array with JitsiTrack objects
 */
function onLocalTracks(tracks) {
    for (let i = 0; i < tracks.length; i++) {
        if (tracks[i].getType() === 'video') {
            if ($('#member-me').data('video-track')) {
                var old_type = $('#member-me').data('video-type');
                $('#member-me').data(`${old_type}-track`).dispose();
                $('#member-me').data(`${old_type}-track`, null);
                $(`#auth-${old_type}`).prop('checked', false);
                $('#member-me').data('video-track').mute();
                room.removeTrack($('#member-me').data('video-track')).then(function(){
                    room.addTrack(tracks[i]);
                });
            } else {
                room.addTrack(tracks[i]);
            }
			if (tracks[i].videoType == 'desktop') {
				$('#member-me').data('screen-track', tracks[i]);
                $('#member-me').data('video-track', tracks[i]);
                $('#member-me').data('video-type', 'screen');
				$('#auth-screen').prop('checked', true);
				$('#member-me .video-status').removeClass('fa-video-slash').addClass('fa-video');
			} else {
				$('#member-me').data('camera-track', tracks[i]);
				$('#member-me').data('video-track', tracks[i]);
                $('#member-me').data('video-type', 'camera');
				$('#auth-camera').prop('checked', true);
				$('#member-me .video-status').removeClass('fa-video-slash').addClass('fa-video');
            }
            tracks[i].attach($('#member-me .member-video')[0]);
            $('#member-me').addClass('has-video');
        } else if (tracks[i].getType() == 'audio') {
			$('#member-me').data('audio-track', tracks[i]);
			$('#auth-microphone').prop('checked', true);
			$('#member-me .microphone-status').removeClass('fa-microphone-alt-slash').addClass('fa-microphone-alt');
			tracks[i].addEventListener(JitsiMeetJS.events.track.TRACK_AUDIO_LEVEL_CHANGED, function(audioLevel) {
				level_changed('me', audioLevel);
			});
            room.addTrack(tracks[i]);
		}
    }
}

var has_audio = false;
$('#attach-audio-button').click(function(e){
	// workaround...
	e.preventDefault();
	if ($('audio.remote').length) {
		var track = $('audio.remote').data('track');
		if (track) {
			track.attach($('audio.remote')[0]);
		}
	}
});

function reportUserList()
{
    var users = [];
    users.push([my_info.slack_id, room.getLocalParticipantProperty("login_at")]);
    for (var id in room.participants) {
        users.push([
            room.participants[id].getProperty('slack_id'),
            room.participants[id].getProperty('login_at')
        ]);
    }
    $.post('/meet/reportuserlist/' + <?= json_encode($this->event->id) ?> + '/' + <?= json_encode($this->channel->channel_id) ?>, 'data=' + encodeURIComponent(JSON.stringify(users)));
}

/**
 * Handles remote tracks
 * @param track JitsiTrack object
 */
function onRemoteTrack(track) {
    if (track.isLocal()) {
        return;
    }
    const participant = track.getParticipantId();

    if (track.getType() === 'video') {
		$(`#member-${participant}`).data('video-track', track);
		if (room.participants[participant].isVideoMuted()) {
			$(`#member-${participant} .video-status`).removeClass('fa-video').addClass('fa-video-slash');
            track.detach($(`#member-${participant} .member-video`)[0]);
            $(`#member-${participant}`).removeClass('has-video')
		} else {
            $(`#member-${participant} .video-status`).removeClass('fa-video-slash').addClass('fa-video');
            $(`#member-${participant}`).addClass('has-video')
            track.attach($(`#member-${participant} .member-video`)[0]);
		}
    } else {
		if (!$(`#member-${participant} audio`).length) {
			$(`#member-${participant}`).append('<audio autoplay="1" class="remote" />');
		}

		if (old_track = $(`#member-${participant} audio`).data('track')) {
			old_track.detach($(`#member-${participant} audio`)[0]);
		}
		track.attach($(`#member-${participant} audio`)[0]);
		$(`#member-${participant} audio`).data('track', track);
		if (room.participants[participant].isAudioMuted()) {
			$(`#member-${participant} .microphone-status`).removeClass('fa-microphone-alt').addClass('fa-microphone-alt-slash');
		} else {
			$(`#member-${participant} .microphone-status`).removeClass('fa-microphone-alt-slash').addClass('fa-microphone-alt');
		}
	}
}

/**
 * That function is executed when the conference is joined
 */

var update_member_list_queue = 0;

var update_member_list = function(){
    if (update_member_list_queue) { // is updating
        update_member_list_queue ++;
        return;
    }
    update_member_list_queue = 1;
    $('.member-box').addClass('checking');
	$('#member-me').removeClass('checking');
    var names = [];
    for (var id in room.participants) {
        var participant = room.participants[id];
        if (null !== participant.getProperty('slack_id')) {
            names.push(participant.getProperty('slack_id'));
        }
    }

    $.get('/event/userinfo/' + <?= json_encode($this->event->id) ?> + '?users=' + encodeURIComponent(names.join(',')), function(ret){
        for (var id in ret.data) {
            user_info[id] = ret.data[id];
        }

        for (var id in room.participants) {
            var participant = room.participants[id];
            if (!$('#member-' + id).length) {
                var member_box = $($('#tmpl-member-box').html());
                member_box.attr('id', `member-${id}`);
                member_box.attr('title', `member-${id}`);
				if (participant.isAudioMuted()) {
					$('.microphone-status', member_box).removeClass('fa-microphone-alt').addClass('fa-microphone-alt-slash');
				} else {
					$('.microphone-status', member_box).removeClass('fa-microphone-alt-slash').addClass('fa-microphone-alt');
				}
				if (participant.isVideoMuted()) {
					$('.video-status', member_box).removeClass('fa-video').addClass('fa-video-slash');
				} else {
					$('.video-status', member_box).removeClass('fa-video-slash').addClass('fa-video');
				}
                $('#member-list').append(member_box);
            }
            $(`#member-${id}`).removeClass('checking');
            if (null !== participant.getProperty('slack_id') && 'undefined' !== typeof(user_info[participant.getProperty('slack_id')])) {
                var info = user_info[participant.getProperty('slack_id')];
                $(`#member-${id} .member-displayname`).text(info.account);
                $(`#member-${id} img`).attr('src', info.avatar);
                $(`#member-${id} .member-image`).show();
                $(`#member-${id} .member-nointro`).hide();
                $(`#member-${id}`).data('info', info);
            } else {
                if (null === participant.getDisplayName()) {
                    displayname = 'Fellow Jitster';
                } else {
                    displayname = participant.getDisplayName();
                }

                $(`#member-${id} .member-displayname`).text(displayname);
                $(`#member-${id} .member-image`).hide();
                $(`#member-${id} .member-nointro`).show();
                $(`#member-${id}`).data('info', null);
            }
        }
        $('.member-box.checking').remove();
        if (update_member_list_queue > 1) {
            update_member_list_queue = 0;
            update_member_list();
        }
        update_member_list_queue = 0;
    }, 'json');
};

var level_changed = function(participant, audioLevel) {
	if (audioLevel > 0) {
		has_audio = true;
		$('#attach-audio-area').hide();
	}
	
	$(`#member-${participant} .v-all`).css('opacity', '0%');
	if (audioLevel >= 1.0) {
		$(`#member-${participant} .v-a`).css('opacity', '100%');
	} else if (audioLevel > 0.8) {
		$(`#member-${participant} .v-a`).css('opacity', '50%');
	}
	if (audioLevel > 0.6) {
		$(`#member-${participant} .v-b`).css('opacity', '100%');
	} else if (audioLevel > 0.4) {
		$(`#member-${participant} .v-b`).css('opacity', '50%');
	}
	if (audioLevel > 0.2) {
		$(`#member-${participant} .v-c`).css('opacity', '100%');
	} else if (audioLevel > 0.01) {
		$(`#member-${participant} .v-c`).css('opacity', '50%');
	}
};

function onConferenceJoined() {
    room.setLocalParticipantProperty('slack_id', my_info.slack_id);
    room.setLocalParticipantProperty('login_at', (new Date()).getTime());
    room.setDisplayName(my_info.account);
    update_member_list();
    reportUserList();
    setInterval(reportUserList, 60000);
    room.on(
        JitsiMeetJS.events.conference.TRACK_AUDIO_LEVEL_CHANGED,
		level_changed
	);

    room.on(JitsiMeetJS.events.conference.USER_JOINED, (id, user) => {
        console.log(id);
        console.log(room.participants);
        update_member_list();
    });
    room.on(JitsiMeetJS.events.conference.DOMINANT_SPEAKER_CHANGED, (id) => {
        $('.member-box').removeClass('member-talking');
        $(`#member-${id}`).addClass('member-talking');
    });
    room.on(JitsiMeetJS.events.conference.USER_LEFT, (id, user) => {
        onUserLeft(id);
        update_member_list();
    });
    room.on(JitsiMeetJS.events.conference.DISPLAY_NAME_CHANGED, (id, user) => {
        update_member_list();
    });
    room.on(JitsiMeetJS.events.conference.PARTICIPANT_PROPERTY_CHANGED, (id, text, ts) => {
        update_member_list();
    });
}

/**
 *
 * @param id
 */
function onUserLeft(id) {
}

/**
 * That function is called when connection is established successfully
 */
function onConnectionSuccess() {
    room = connection.initJitsiConference(confOptions.confID, confOptions);
    room.on(JitsiMeetJS.events.conference.TRACK_ADDED, onRemoteTrack);
    room.on(JitsiMeetJS.events.conference.TRACK_REMOVED, track => {
        console.log(`track removed!!!${track}`);
    });
    room.on(
        JitsiMeetJS.events.conference.CONFERENCE_JOINED,
        onConferenceJoined);

    room.on(JitsiMeetJS.events.conference.TRACK_MUTE_CHANGED, track => {
		var id = track.ownerEndpointId;
		if (track.getType() == 'video') {
			if (track.muted) {
                track.detach($(`#member-${id} .member-video`)[0]);
                $(`#member-${id}`).removeClass('has-video')
				$(`#member-${id} .video-status`).removeClass('fa-video').addClass('fa-video-slash');
			} else {
                $(`#member-${id}`).addClass('has-video')
                track.attach($(`#member-${id} .member-video`)[0]);
				$(`#member-${id} .video-status`).removeClass('fa-video-slash').addClass('fa-video');
			}
		} else {
			if (track.muted) {
				$(`#member-${id} .microphone-status`).removeClass('fa-microphone-alt').addClass('fa-microphone-alt-slash');
			} else {
				$(`#member-${id} .microphone-status`).removeClass('fa-microphone-alt-slash').addClass('fa-microphone-alt');
			}
		}
    });
    room.join();
}

function onConnectionFailed() {
    alert('Connection Failed!');
}

function disconnect() {
    connection.removeEventListener(
        JitsiMeetJS.events.connection.CONNECTION_ESTABLISHED,
        onConnectionSuccess);
    connection.removeEventListener(
        JitsiMeetJS.events.connection.CONNECTION_FAILED,
        onConnectionFailed);
    connection.removeEventListener(
        JitsiMeetJS.events.connection.CONNECTION_DISCONNECTED,
        disconnect);
}

function unload() {
    room.leave();
    connection.disconnect();
}

$('.main-switch').click(function(e){
	e.preventDefault();
	var tab = $(this).attr('id').split('-')[2];
	$('.main-area-section').hide();
	$('#main-area-' + tab).show();
	$('.main-switch').removeClass('active');
	$(this).addClass('active');
	
});

let isVideo = true;

$(window).bind('beforeunload', unload);
$(window).bind('unload', unload);

JitsiMeetJS.setLogLevel(JitsiMeetJS.logLevels.ERROR);
const initOptions = {
    disableAudioLevels: false,

    // The ID of the jidesha extension for Chrome.
    desktopSharingChromeExtId: 'mbocklcggfhnbahlnepmldehdhpjfcjp',

    // Whether desktop sharing should be disabled on Chrome.
    desktopSharingChromeDisabled: false,

    // The media sources to use when using screen sharing with the Chrome
    // extension.
    desktopSharingChromeSources: [ 'screen', 'window' ],

    // Required version of Chrome extension
    desktopSharingChromeMinExtVersion: '0.1',

    // Whether desktop sharing should be disabled on Firefox.
    desktopSharingFirefoxDisabled: true
};

var user_info = {};
var my_info;

$.get('/meet/data/' + <?= json_encode($this->event->id) ?> + '/' + <?= json_encode($this->channel->channel_id) ?>, function(ret){
    confOptions.confID = ret.meta.jitsi_room;
    my_info = ret.user;
	$('#member-me .member-image').attr('src', ret.user.avatar);
	$('#member-me').show();
    $('#title').val(ret.meta.title);

    JitsiMeetJS.init(initOptions);

    connection = new JitsiMeetJS.JitsiConnection(null, null, options);

    connection.addEventListener(
        JitsiMeetJS.events.connection.CONNECTION_ESTABLISHED,
        onConnectionSuccess);
    connection.addEventListener(
        JitsiMeetJS.events.connection.CONNECTION_FAILED,
        onConnectionFailed);
    connection.addEventListener(
        JitsiMeetJS.events.connection.CONNECTION_DISCONNECTED,
        disconnect);

    connection.connect();

	if (JitsiMeetJS.mediaDevices.isDeviceChangeAvailable('output')) {
		JitsiMeetJS.mediaDevices.enumerateDevices(devices => {
			const audioOutputDevices
				= devices.filter(d => d.kind === 'audiooutput');

			if (audioOutputDevices.length >= 1) {
				JitsiMeetJS.mediaDevices.setAudioOutputDevice(audioOutputDevices[0].deviceId);
			}
		});
	}

}, 'json');

$('#auth-screen').change(function(e){
	e.preventDefault();

	var screen_track = $('#member-me').data('screen-track');
	if (!screen_track) {
		JitsiMeetJS.createLocalTracks({ devices: [ 'desktop' ] })
			.then(onLocalTracks)
			.catch(error => {
				throw error;
		});
	} else {
		if (screen_track.isMuted()) {
			screen_track.unmute().then(function(){
				$('#auth-screen').prop('checked', true);
				$('#auth-camera').prop('checked', false);
                $('#member-me').addClass('has-video');
                screen_track.attach($('#member-me .member-video')[0]);
				$(`#member-me .video-status`).removeClass('fa-video-alt-slash').addClass('fa-video-alt');
			});
        } else {
            $('#member-me').data('screen-track', null);
            screen_track.mute().then(function(){
				$('#auth-screen').prop('checked', false);
                $('#member-me').removeClass('has-video');
                screen_track.detach($('#member-me .member-video')[0]);
				$(`#member-me .video-status`).removeClass('fa-video-alt').addClass('fa-video-alt-slash');
			});
		}
	}
});

$('#auth-camera').change(function(e){
	e.preventDefault();

	var camera_track = $('#member-me').data('camera-track');
	if (!camera_track) {
		JitsiMeetJS.createLocalTracks({ devices: [ 'video' ] })
			.then(onLocalTracks)
			.catch(error => {
				throw error;
		});
	} else {
		if (camera_track.isMuted()) {
			camera_track.unmute().then(function(){
				$('#auth-camera').prop('checked', true);
				$('#auth-screen').prop('checked', false);
                $('#member-me').addClass('has-video');
                camera_track.attach($('#member-me .member-video')[0]);
				$(`#member-me .video-status`).removeClass('fa-video-alt-slash').addClass('fa-video-alt');
			});
        } else {
            $('#member-me').data('camera-track', null)
			camera_track.mute().then(function(){
				$('#auth-camera').prop('checked', false);
                $('#member-me').removeClass('has-video');
                camera_track.detach($('#member-me .member-video')[0]);
				$(`#member-me .video-status`).removeClass('fa-video-alt').addClass('fa-video-alt-slash');
			});
		}
	}
});

$('#auth-microphone').change(function(e){
	e.preventDefault();

	var audio_track = $('#member-me').data('audio-track');
	if (!audio_track) {
		JitsiMeetJS.createLocalTracks({ devices: [ 'audio' ] })
			.then(onLocalTracks)
			.catch(error => {
				throw error;
		});
	} else {
		if (audio_track.isMuted()) {
			audio_track.unmute().then(function(){
				$('#auth-microphone').prop('checked', true);
				$(`#member-me .microphone-status`).removeClass('fa-microphone-alt-slash').addClass('fa-microphone-alt');
			});
		} else {
			audio_track.mute().then(function(){
				$('#auth-microphone').prop('checked', false);
				$(`#member-me .microphone-status`).removeClass('fa-microphone-alt').addClass('fa-microphone-alt-slash');
			});
		}
	}
});

$('#member-list').on('click', '.member-box', function(e){
	e.preventDefault();
	var track = $(this).data('video-track');
	if (track && !track.muted) {
		track_video_attach(track);
	}
});

</script>
<?= $this->partial('common/footer.phtml', $this) ?>
