<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>g0ver 自我介紹 Self Introduction</title>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<script src="//ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.css">
<script type="text/javascript">
<?php if (getenv('GOOGLEANALYTICS_ACCOUNT')) { ?>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=<?= urlencode(getenv('GOOGLEANALYTICS_ACCOUNT')) ?>"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', <?= json_encode(getenv('GOOGLEANALYTICS_ACCOUNT')) ?>);
</script>
<?php } ?>

</head>
<body class="<?= $this->escape($this->body_class) ?>">
<div class="container-fluid">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">g0ver 自我介紹 Self Introduction</a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
            <?php if (!$this->user) { ?>
            <li class="nav-item">
            <a class="nav-link" href="/login/?next=<?= urlencode($_SERVER['REQUEST_URI']) ?>">登入 Sign In</a>
            </li>
            <?php } else { ?>
            <?php if ($this->user->type == 2) { ?>
            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="adminDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">管理者功能</a>
            <div class="dropdown-menu" aria-labelledby="adminDropdown">
                <a class="dropdown-item" href="/admin/event">活動管理 Event</a>
                <a class="dropdown-item" href="/admin/member">成員管理 Member</a>
			</div>
            </li>
            <?php } ?>
            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Hi! <?= $this->escape($this->user->account) ?></a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="/login/logout?next=<?= urlencode($_SERVER['REQUEST_URI']) ?>">登出 Sign Out</a>
			</div>
            </li>
            <?php } ?>
        </ul>
    </div>
</nav>
    <div class="row-fluid">
